Controllers/AuctionModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CraigList.Data;
using CraigList.Models;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace CraigList.Controllers
{
    public class AuctionModelsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public IWebHostEnvironment WebHostEnvironment;
        private readonly UserManager<ApplicationUser> _userManager;


        public AuctionModelsController(ApplicationDbContext context,IWebHostEnvironment webHostEnvironment, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
            WebHostEnvironment = webHostEnvironment;
        }

        /// <summary>
        /// Return view of all your auctions
        /// </summary>
        /// <returns></returns>
        // GET: AuctionModels
        public async Task<IActionResult> Index()
        {
            var all = await _context.AuctionModel.ToListAsync();

            List<AuctionModel> thisUserAuctions = new List<AuctionModel>();
            var user = await _userManager.GetUserAsync(HttpContext.User);

            foreach (var item in all)
            {
                if (item.UserId == user.Id)
                {
                    thisUserAuctions.Add(item);
                }
            }

            return View(thisUserAuctions);
        }

        /// <summary>
        /// open view with details of specific auction
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: AuctionModels/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var auctionModel = await _context.AuctionModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (auctionModel == null)
            {
                return NotFound();
            }

            return View(auctionModel);
        }

        /// <summary>
        /// get of create method
        /// </summary>
        /// <returns></returns>
        // GET: AuctionModels/Create
        public IActionResult Create()
        {
            return View(new CreateAuctionModel());
        }

        /// <summary>
        /// creates new entry with auction model 
        /// </summary>
        /// <param name="createAuctionModel"></param>
        /// <returns></returns>
        // POST: AuctionModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Price,Picture")] CreateAuctionModel createAuctionModel)
        {
            string fileName = "nie ma";
            if (createAuctionModel.Picture != null)
            {
                fileName = UploadFile(createAuctionModel);
            }

            var user = await _userManager.GetUserAsync(HttpContext.User);

            var auctionModel = new AuctionModel
            {
                UserId = user.Id,
                Price = createAuctionModel.Price,
                Title = createAuctionModel.Title,
                Description = createAuctionModel.Description,
                Picture = fileName,
                EndDate = DateTime.Now.AddDays(14)
            };

            if (ModelState.IsValid)
            {
                _context.Add(auctionModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(createAuctionModel);
        }

        /// <summary>
        /// worst method on earth that uploads image to Img folder in wwwroot xD
        /// </summary>
        /// <param name="createAuctionModel"></param>
        /// <returns></returns>
        private string UploadFile(CreateAuctionModel createAuctionModel)
        {
            string fileName = null;
            if (createAuctionModel != null)
            {
                string uploadDir = Path.Combine(WebHostEnvironment.WebRootPath, "Img");
                fileName = Guid.NewGuid().ToString() + "-" + createAuctionModel.Picture.FileName;
                string filePath = Path.Combine(uploadDir, fileName);
                using (var fileStream = new FileStream(filePath,FileMode.Create)) 
                {
                    createAuctionModel.Picture.CopyTo(fileStream);
                }
            }
            return fileName;
        }

        /// <summary>
        /// returns list of cards with all active auctions
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Auctions() 
        {
            var auctions = await _context.AuctionModel.ToListAsync();

            List<AuctionModel> active = new List<AuctionModel>();
            foreach (var item in auctions)
            {
                if (item.EndDate < DateTime.Now)
                {
                    active.Add(item);
                }
            }
            return View(auctions);
        }

        /// <summary>
        /// display more info of specific auction
        /// </summary>
        /// <param name="auctionId"></param>
        /// <returns></returns>
        public async Task<IActionResult> DisplayAuction(string auctionId)
        {
            

            if (auctionId == null)
            {
                return NotFound();
            }

            var auctionModel = await _context.AuctionModel.FindAsync(auctionId);
            if (auctionModel == null)
            {
                return NotFound();
            }
            var user = await _userManager.FindByIdAsync(auctionModel.UserId);
            Tuple<AuctionModel, ApplicationUser> auctionWithOwner = new Tuple<AuctionModel, ApplicationUser>(auctionModel, user);

            return View(auctionWithOwner);
        }

        /// <summary>
        /// opens view of delete function
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: AuctionModels/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var auctionModel = await _context.AuctionModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (auctionModel == null)
            {
                return NotFound();
            }

            return View(auctionModel);
        }

        /// <summary>
        /// deletes auction entry
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // POST: AuctionModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var auctionModel = await _context.AuctionModel.FindAsync(id);
            _context.AuctionModel.Remove(auctionModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AuctionModelExists(string id)
        {
            return _context.AuctionModel.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CraigList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <img src="https://localhost:44305/Images/CraigLogo.png" style="width:100px;height:100px;" />
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CraigList</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AuctionModels" asp-action="Auctions">Auctions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AuctionModels" asp-action="Index">My Auctions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AuctionModels" asp-action="Create">Add Auctions</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CraigList - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>